# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server.port: 8090

logging.level.com.arahansa: DEBUG

spring:
  resources:
    chain:
      compressed: true